/**:
  ros__parameters:
    gait:
      knee_orientation: ">>"
      pantograph_leg: false
      odom_scaler: 0.9
      max_linear_velocity_x: 0.18
      max_linear_velocity_y: 0.08
      max_angular_velocity_z: 0.4
      com_x_translation: 0.0
      swing_height: 0.025
      stance_depth: 0.006
      stance_duration: 0.32
      nominal_height: 0.155